Prefecture.create( id: 1, prefecture: '北海道')
Prefecture.create( id: 2, prefecture: '青森県')
Prefecture.create( id: 3, prefecture: '岩手県')
Prefecture.create( id: 4, prefecture: '宮城県')
Prefecture.create( id: 5, prefecture: '秋田県')
Prefecture.create( id: 6, prefecture: '山形県')
Prefecture.create( id: 7, prefecture: '福島県')
Prefecture.create( id: 8, prefecture: '茨城県')
Prefecture.create( id: 9, prefecture: '栃木県')
Prefecture.create( id: 10, prefecture: '群馬県')
Prefecture.create( id: 11, prefecture: '埼玉県')
Prefecture.create( id: 12, prefecture: '千葉県')
Prefecture.create( id: 13, prefecture: '東京都')
Prefecture.create( id: 14, prefecture: '神奈川県')
Prefecture.create( id: 15, prefecture: '山梨県')
Prefecture.create( id: 16, prefecture: '長野県')
Prefecture.create( id: 17, prefecture: '新潟県')
Prefecture.create( id: 18, prefecture: '富山県')
Prefecture.create( id: 19, prefecture: '石川県')
Prefecture.create( id: 20, prefecture: '福井県')
Prefecture.create( id: 21, prefecture: '岐阜県')
Prefecture.create( id: 22, prefecture: '静岡県')
Prefecture.create( id: 23, prefecture: '愛知県')
Prefecture.create( id: 24, prefecture: '三重県')
Prefecture.create( id: 25, prefecture: '滋賀県')
Prefecture.create( id: 26, prefecture: '京都府')
Prefecture.create( id: 27, prefecture: '大阪府')
Prefecture.create( id: 28, prefecture: '兵庫県')
Prefecture.create( id: 29, prefecture: '奈良県')
Prefecture.create( id: 30, prefecture: '和歌山県')
Prefecture.create( id: 31, prefecture: '鳥取県')
Prefecture.create( id: 32, prefecture: '島根県')
Prefecture.create( id: 33, prefecture: '岡山県')
Prefecture.create( id: 34, prefecture: '広島県')
Prefecture.create( id: 35, prefecture: '山口県')
Prefecture.create( id: 36, prefecture: '徳島県')
Prefecture.create( id: 37, prefecture: '香川県')
Prefecture.create( id: 38, prefecture: '愛媛県')
Prefecture.create( id: 39, prefecture: '高知県')
Prefecture.create( id: 40, prefecture: '福岡県')
Prefecture.create( id: 41, prefecture: '佐賀県')
Prefecture.create( id: 42, prefecture: '長崎県')
Prefecture.create( id: 43, prefecture: '熊本県')
Prefecture.create( id: 44, prefecture: '大分県')
Prefecture.create( id: 45, prefecture: '宮崎県')
Prefecture.create( id: 46, prefecture: '鹿児島県')
Prefecture.create( id: 47, prefecture: '沖縄県')

CleanCompany.create( id: 1, user_id: 8,name: '会社名A',tel: '0311112222',email: 'maesong.from.badcity@cmail.com',image_url:'img1.jpeg')
CleanCompany.create( id: 2, user_id: 8,name: '会社名B',tel: '0333334444',email: 'maesong.from.badcity@wahoo.com',image_url:'img2.jpeg')
CleanCompany.create( id: 3, user_id: 8,name: '会社名C',tel: '0355556666',email: 'maesong.from.badcity@wahoo.co.jp',image_url:'img3.jpeg')
CleanCompany.create( id: 4, user_id: 8,name: 'test',tel: '012033331111',email: 'test@email.com',image_url:'img4.jpg')
CleanCompany.create( id: 5, user_id: 8,name: 'Mクリーンズ',tel: '0120111555',email: 'test@cleanmail.com',image_url:'img5.jpg')
CleanCompany.create( id: 6, user_id: 8,name: 'どこでもメンテ',tel: '0311112222',email: 'ouwuwwo@mail.com',image_url:'7808725.jpg')
CleanCompany.create( id: 7, user_id: 8,name: '頑張るメンテ',tel: '0333334444',email: 'ganbaru@email.com',image_url:'homemaker-work-d-02.jpg')
CleanCompany.create( id: 8, user_id: 8,name: '東京サービス',tel: '0355556666',email: 'tokyo@mail.com',image_url:'images__1_.jpg')
CleanCompany.create( id: 9, user_id: 8,name: '埼玉サービス',tel: '012033331111',email: 'saitama@mail.com',image_url:'images__3_.jpg')
CleanCompany.create( id: 10, user_id: 8,name: '茨城メンテ',tel: '0120111555',email: 'ibaraki@mail.com',image_url:'images.jpg')
CleanCompany.create( id: 11, user_id: 8,name: '群馬メンテ',tel: '0311112222',email: 'gnma@mail.com',image_url:'特殊清掃_害虫駆除.jpg')
CleanCompany.create( id: 12, user_id: 8,name: '栃木メンテ',tel: '0333334444',email: 'tochigi@gmail.com',image_url:'images__2_.jpg')
CleanCompany.create( id: 13, user_id: 8,name: '群馬メンテ',tel: '0355556666',email: 'gunma@email.com',image_url:'img03.jpg')
CleanCompany.create( id: 14, user_id: 8,name: '大阪サービス',tel: '012033331111',email: 'osaka@mail.com',image_url:'self-room-001.jpg')
CleanCompany.create( id: 15, user_id: 8,name: '京都メンテ',tel: '0120111555',email: 'kyoto@mail.com',image_url:'icatch3.jpg')
CleanCompany.create( id: 16, user_id: 8,name: '滋賀メンテ',tel: '0311112222',email: 'shiga@mail.com',image_url:'images__1_.jpg')
CleanCompany.create( id: 17, user_id: 8,name: '和歌山クリン',tel: '0333334444',email: 'waka@mail.com',image_url:'images.jpeg')
CleanCompany.create( id: 18, user_id: 8,name: '奈良クリン',tel: '0355556666',email: 'nara@mail.com',image_url:'homemaker-work-d-02.jpg')
CleanCompany.create( id: 19, user_id: 8,name: '兵庫クリーン',tel: '012033331111',email: 'hyogo@mail.com',image_url:'7808725.jpg')



CleanReview.create( id: 1, user_id: 1, clean_company_id: 1, point: '4.5', comment: 'とても、綺麗にしてくださいました。始末後の連絡も丁寧でした。また、お願いします。')
CleanReview.create( id: 2, user_id: 4, clean_company_id: 1, point: '5', comment: '素晴らしいです')
CleanReview.create( id: 3, user_id: 3, clean_company_id: 1, point: '4', comment: '連絡もスムーズでした')
CleanReview.create( id: 4, user_id: 6, clean_company_id: 1, point: '5', comment: '親切丁寧な仕事ぶりでした')
CleanReview.create( id: 5, user_id: 7, clean_company_id: 1, point: '5', comment: '最高')

Charge.create( id: 1, clean_company_id: 1, square_meters_min: '0', square_meters_max: '20', charge:'4000')
Charge.create( id: 2, clean_company_id: 1, square_meters_min: '20.1', square_meters_max: '50', charge:'5000')
Charge.create( id: 3, clean_company_id: 1, square_meters_min: '50.1', square_meters_max: '80', charge:'6000')
Charge.create( id: 4, clean_company_id: 6, square_meters_min: '0', square_meters_max: '10', charge:'2000')
Charge.create( id: 5, clean_company_id: 7, square_meters_min: '0', square_meters_max: '10', charge:'1000')
Charge.create( id: 6, clean_company_id: 7, square_meters_min: '10.1', square_meters_max: '20', charge:'2000')
Charge.create( id: 7, clean_company_id: 8, square_meters_min: '0', square_meters_max: '10', charge:'3000')
Charge.create( id: 8, clean_company_id: 8, square_meters_min: '10.1', square_meters_max: '20', charge:'3500')
Charge.create( id: 9, clean_company_id: 10, square_meters_min: '0', square_meters_max: '10', charge:'2000')
Charge.create( id: 10, clean_company_id: 10, square_meters_min: '10.1', square_meters_max: '20', charge:'3000')
Charge.create( id: 11, clean_company_id: 11, square_meters_min: '0', square_meters_max: '10', charge:'4000')
Charge.create( id: 12, clean_company_id: 11, square_meters_min: '10.1', square_meters_max: '20', charge:'5000')
Charge.create( id: 13, clean_company_id: 13, square_meters_min: '0', square_meters_max: '10', charge:'3000')
Charge.create( id: 14, clean_company_id: 14, square_meters_min: '0', square_meters_max: '10', charge:'1000')
Charge.create( id: 15, clean_company_id: 14, square_meters_min: '10.1', square_meters_max: '20', charge:'2000')
Charge.create( id: 16, clean_company_id: 15, square_meters_min: '0', square_meters_max: '10', charge:'1000')
Charge.create( id: 17, clean_company_id: 18, square_meters_min: '0', square_meters_max: '10', charge:'1000')
Charge.create( id: 18, clean_company_id: 18, square_meters_min: '10.1', square_meters_max: '20', charge:'3000')
Charge.create( id: 19, clean_company_id: 19, square_meters_min: '0', square_meters_max: '10', charge:'1000')
Charge.create( id: 20, clean_company_id: 19, square_meters_min: '10.1', square_meters_max: '20', charge:'2000')
Charge.create( id: 21, clean_company_id: 19, square_meters_min: '20.1', square_meters_max: '30', charge:'4000')

CleanPrefecture.create( id: 1, clean_company_id: 1, prefecture_id: 12)
CleanPrefecture.create( id: 2, clean_company_id: 1, prefecture_id: 13)
CleanPrefecture.create( id: 3, clean_company_id: 1, prefecture_id: 11)
CleanPrefecture.create( id: 4, clean_company_id: 1, prefecture_id: 14)
CleanPrefecture.create( id: 5, clean_company_id: 6, prefecture_id: 13)
CleanPrefecture.create( id: 6, clean_company_id: 7, prefecture_id: 14)
CleanPrefecture.create( id: 7, clean_company_id: 7, prefecture_id: 11)
CleanPrefecture.create( id: 8, clean_company_id: 7, prefecture_id: 12)
CleanPrefecture.create( id: 9, clean_company_id: 8, prefecture_id: 13)
CleanPrefecture.create( id: 10, clean_company_id: 8, prefecture_id: 14)
CleanPrefecture.create( id: 11, clean_company_id: 9, prefecture_id: 11)
CleanPrefecture.create( id: 12, clean_company_id: 10, prefecture_id: 12)
CleanPrefecture.create( id: 13, clean_company_id: 10, prefecture_id: 8)
CleanPrefecture.create( id: 14, clean_company_id: 11, prefecture_id: 10)
CleanPrefecture.create( id: 15, clean_company_id: 12, prefecture_id: 9)
CleanPrefecture.create( id: 16, clean_company_id: 13, prefecture_id: 10)
CleanPrefecture.create( id: 17, clean_company_id: 14, prefecture_id: 27)
CleanPrefecture.create( id: 18, clean_company_id: 15, prefecture_id: 26)
CleanPrefecture.create( id: 19, clean_company_id: 16, prefecture_id: 25)
CleanPrefecture.create( id: 20, clean_company_id: 17, prefecture_id: 30)
CleanPrefecture.create( id: 21, clean_company_id: 18, prefecture_id: 29)
CleanPrefecture.create( id: 22, clean_company_id: 19, prefecture_id: 28)



User.create( id: 1, name: 'maesonger', account_type: 1, email: 'maesong.from.badcity@gmail.com', tel: '0726832214', password: 'uhikki58')
User.create( id: 2, name: 'test1', account_type: 1, email: 'test1@email.com', tel: '11111111', password: 'uhikki58')
User.create( id: 3, name: '前田', account_type: 1, email: 'maesong.from.badcity@yahoo.co.jp', tel: '0726242282', password: 'uhikki58')
User.create( id: 4, name: '知英', account_type: 1, email: 'maesong_from_badcity@yahoo.co.jp', tel: '0726242282', password: 'uhikki58')
User.create( id: 5, name: '吉田', account_type: 1, email: 'y.yoshida22@gmail.com', tel: '00011112222', password: 'uhikki58')
User.create( id: 6, name: 'マエソン', account_type: 1, email: 'maesong_from_badcity@ezweb.ne.jp', tel: '0728598392', password: 'uhikki58')
User.create( id: 7, name: 'マエだ', account_type: 1, email: 'maeson@email.com', tel: '0726832214', password: 'uhikki58')
User.create( id: 8, name: 'Mメンテナンス', account_type: 2, email: 'maesong@email.com', tel: '0726242282', password: 'uhikki58')