CleanCompany.create( id: 1, user_id: 8,name: '会社名A',tel: '0311112222',email: 'maesong.from.badcity@cmail.com',image_url:'img1.jpeg')
CleanCompany.create( id: 2, user_id: 8,name: '会社名B',tel: '0333334444',email: 'maesong.from.badcity@wahoo.com',image_url:'img2.jpeg')
CleanCompany.create( id: 3, user_id: 8,name: '会社名C',tel: '0355556666',email: 'maesong.from.badcity@wahoo.co.jp',image_url:'img3.jpeg')
CleanCompany.create( id: 4, user_id: 8,name: 'test',tel: '012033331111',email: 'test@email.com',image_url:'img4.jpg')
CleanCompany.create( id: 5, user_id: 8,name: 'Mクリーンズ',tel: '0120111555',email: 'test@cleanmail.com',image_url:'img5.jpg')

CleanReview.create( id: 1, user_id: 1, clean_company_id: 1, point: '4.5', comment: 'とても、綺麗にしてくださいました。始末後の連絡も丁寧でした。また、お願いします。')
CleanReview.create( id: 2, user_id: 4, clean_company_id: 1, point: '5', comment: '素晴らしいです')
CleanReview.create( id: 3, user_id: 3, clean_company_id: 1, point: '4', comment: '連絡もスムーズでした')
CleanReview.create( id: 4, user_id: 6, clean_company_id: 1, point: '5', comment: '親切丁寧な仕事ぶりでした')
CleanReview.create( id: 5, user_id: 7, clean_company_id: 1, point: '5', comment: '最高')

Charge.create( id: 1, clean_company_id: 1, square_meters_min: '0', square_meters_max: '20', charge:'4000')
Charge.create( id: 2, clean_company_id: 1, square_meters_min: '20.1', square_meters_max: '50', charge:'5000')
Charge.create( id: 3, clean_company_id: 1, square_meters_min: '50.1', square_meters_max: '80', charge:'6000')

CleanPrefecture.create( id: 1, clean_company_id: 1, prefecture_id: 12)
CleanPrefecture.create( id: 2, clean_company_id: 1, prefecture_id: 13)
CleanPrefecture.create( id: 3, clean_company_id: 1, prefecture_id: 11)
CleanPrefecture.create( id: 4, clean_company_id: 1, prefecture_id: 14)